SPLITERCON_TALK = {'RU','UA','KZ','BY'}

EX_SOVIET_COUNTRIES = {
    "AM": "Armenia", "AZ": "Azerbaijan", "BY": "Belarus", "EE": "Estonia", "GE": "Georgia", "KZ": "Kazakhstan",
    "KG": "Kyrgyzstan", "LV": "Latvia", "LT": "Lithuania", "MD": "Moldova", "RU": "Russia", "TJ": "Tajikistan",
    "TM": "Turkmenistan", "UA": "Ukraine", "UZ": "Uzbekistan"
}

REPORT_COUNTRIES = {
    'AF': 'Afghanistan',
    'AR': 'Argentina',
    'AM': 'Armenia',
    'AZ': 'Azerbaijan',
    'BD': 'Bangladesh',
    'BY': 'Belarus',
    'BR': 'Brazil',
    'BG': 'Bulgaria',
    'KH': 'Cambodia',
    'CM': 'Cameroon',
    'CA': 'Canada',
    'CF': 'Central African Republic',
    'TD': 'Chad',
    'CL': 'Chile',
    'CN': 'China',
    'CO': 'Colombia',
    'CG': 'Congo',
    'CD': 'Congo Democratic Republic',
    'CR': 'Costa Rica',
    'CU': 'Cuba',
    'CZ': 'Czechia',
    'DK': 'Denmark',
    'EC': 'Ecuador',
    'EG': 'Egypt',
    'ER': 'Eritrea',
    'EE': 'Estonia',
    'ET': 'Ethiopia',
    'FI': 'Finland',
    'FR': 'France',
    'GA': 'Gabon',
    'GM': 'Gambia',
    'GE': 'Georgia',
    'DE': 'Germany',
    'GH': 'Ghana',
    'GR': 'Greece',
    'HK': 'Hong Kong',
    'HU': 'Hungary',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR': 'Iran, Islamic Republic of',
    'IQ': 'Iraq',
    'IL': 'Israel',
    'IT': 'Italy',
    'JO': 'Jordan',
    'KZ': 'Kazakhstan',
    'KE': 'Kenya',
    'KP': "Korea Democratic People's Republic",
    'KR': 'Korea, Republic of',
    'KW': 'Kuwait',
    'KG': 'Kyrgyzstan',
    'LA': "Lao People's Democratic Republic",
    'LV': 'Latvia',
    'LB': 'Lebanon',
    'LY': 'Libya',
    'LT': 'Lithuania',
    'MY': 'Malaysia',
    'ML': 'Mali',
    'MR': 'Mauritania',
    'MX': 'Mexico',
    'MD': 'Moldova, Republic of',
    'MN': 'Mongolia',
    'ME': 'Montenegro',
    'MZ': 'Mozambique',
    'MM': 'Myanmar',
    'NA': 'Namibia',
    'NL': 'Netherlands, Kingdom of the',
    'NI': 'Nicaragua',
    'NE': 'Niger',
    'NG': 'Nigeria',
    'MK': 'North Macedonia',
    'OM': 'Oman',
    'PK': 'Pakistan',
    'PS': 'Palestine, State of',
    'PG': 'Papua New Guinea',
    'PY': 'Paraguay',
    'PE': 'Peru',
    'PH': 'Philippines',
    'PL': 'Poland',
    'PT': 'Portugal',
    'QA': 'Qatar',
    'RO': 'Romania',
    'RU': 'Russian Federation',
    'RW': 'Rwanda',
    'SA': 'Saudi Arabia',
    'SN': 'Senegal',
    'RS': 'Serbia',
    'SG': 'Singapore',
    'SO': 'Somalia',
    'ZA': 'South Africa',
    'SS': 'South Sudan',
    'SD': 'Sudan',
    'SR': 'Suriname',
    'TW': 'Taiwan, Province of China',
    'TJ': 'Tajikistan',
    'TZ': 'Tanzania, United Republic of',
    'TH': 'Thailand',
    'TN': 'Tunisia',
    'TR': 'Türkiye',
    'TM': 'Turkmenistan',
    'UG': 'Uganda',
    'UA': 'Ukraine',
    'AE': 'United Arab Emirates',
    'GB': 'United Kingdom of Great Britain and Northern Ireland',
    'US': 'United States of America',
    'UY': 'Uruguay',
    'UZ': 'Uzbekistan',
    'VE': 'Venezuela, Bolivarian Republic of',
    'VN': 'Viet Nam',
    'YE': 'Yemen',
    'ZM': 'Zambia',
    'ZW': 'Zimbabwe'
}
